language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install: npm install
script:
  - bash ./deploy/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "819fc46662f4"
    - COMMIT_AUTHOR_EMAIL: "admin@hackzzila.com"
dist: trusty
sudo: false